### ISSUE TITLE
Client refreshing and menu not available

### ISSUE THREAD

**Issue by atanu-sw** [iDempiere-micro/erpjs#140]
Running in local with Keycloack in docker and PostgreSQL in clound. Client is refreshing continously and menu is not getting published.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/25636407/161375658-0ef63b43-c8c3-48e7-b372-07593ac6d964.png">

**Comment by davidpodhola** [comment]
Thanks for reporting this, could you maybe please have a look at the network tab with the "Preserve log" turned on?

**Comment by kubeworkz** [comment]
Me too. Preserve log, from what I could tell, was displaying a lot of 0's for requests and responses.

**Comment by phemieny7** [comment]
The error might come from you changing the default `TECHNICAL_USER_EMAIL`  to your preferred email, if this is what you did,  then try change the default email in the `USER`  in your database to same as you choose for `TECHNICAL_USER_EMAIL`. This solve  the issue for me
![Capture](https://user-images.githubusercontent.com/10562193/181118736-a253be67-f334-4aaf-b8b9-ba7515884688.PNG)

**Comment by davidpodhola** [comment]
Closing the issue as it seems to be resolved, please feel free to comment should that happen again.
